//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXYOnlineJudge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int problem_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string input { get; set; }
        public string output { get; set; }
        public string sample_input { get; set; }
        public string sample_output { get; set; }
        public string hint { get; set; }
        public string spj { get; set; }
        public string source { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<int> time_limit { get; set; }
        public Nullable<int> memory_limit { get; set; }
        public string enable { get; set; }
        public Nullable<int> accepted { get; set; }
        public Nullable<int> submit { get; set; }
        public string solved { get; set; }
    }
}
