//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXYOnlineJudge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int solution_id { get; set; }
        public int problem_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> memory { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<int> result { get; set; }
        public string language { get; set; }
        public string ip { get; set; }
        public Nullable<int> contest_id { get; set; }
        public Nullable<int> valid { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> code_length { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> uploadtime { get; set; }
    }
}
