//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXYOnlineJudge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string user_id { get; set; }
        public string email { get; set; }
        public Nullable<int> submit { get; set; }
        public Nullable<int> solved { get; set; }
        public string defunct { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> reg_time { get; set; }
        public string password { get; set; }
        public string nick { get; set; }
        public string school { get; set; }
    }
}
